# Generated by Django 5.0.3 on 2024-03-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240312_0100'),
    ]

    operations = [
    ]
