# Generated by Django 5.0.3 on 2024-03-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_todoitem_image_alter_todoitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='image',
        ),
    ]
