# Generated by Django 5.0.3 on 2024-03-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
