# Generated by Django 5.0.3 on 2024-03-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_todoitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='echoitem',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
