# Generated by Django 5.0.3 on 2024-03-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_echoitem_user_id_todoitem_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echoitem',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='user_id',
        ),
    ]
